### ISSUE TITLE
MPS creates uncraftable recipes

### ISSUE THREAD

**Issue by japherwocky** [japherwocky/japherpack#3]
MPS creates a recipe file initially, but recipes show in NEI as "JSON Formed", and don't seem to be craftable.

**Comment by superckl** [comment]
Recipes actually work, they are just not registering properly in NEI. Recipes can be found in 

```
nolimyn/config/machinemuse/recipes/mps-enderio.recipes
```

**Comment by japherwocky** [comment]
progress on the charging issue also https://github.com/MachineMuse/MachineMusePowersuits/issues/629
